### ISSUE TITLE
Solve the Cairo problem

### ISSUE THREAD

**Issue by shawninder** [vigour-io/imaginate#9]
For some reason, Cairo won't install normally via npm so the imaginator doesn't work with travis or nowjs. I don't know what the best way to tackle this is... @jimdebeer ?

**Comment by shawninder** [comment]
Trying with Docker but it's not being easy.

**Comment by jimdebeer** [comment]
you have to make a postinstall script for it to install cairo

**Comment by shawninder** [comment]
@jimdebeer I'm installing Cairo in the Dockerfile

`RUN apt-get update && apt-get install libcairo2-dev && apt-get clean && rm -rf /var/lib/apt/lists/*`

Would it be better in a postinstall npm script? Seems more fitting in the Dockerfile since it's OS-dependant and the OS is determined in that same file...

**Comment by jimdebeer** [comment]
hmm doesnt cairo just have a `cmake` or something in it?

**Comment by jimdebeer** [comment]
prob works like shit

**Comment by shawninder** [comment]
Ok I found the issue: 
`npm install` was installing more stuff than necessary, and thus had to uninstall a lot of modules before launching, taking a whole lot of time, giving the impressions that the process had stopped and wasn’t working. The solution was to use `npm install --production` instead of `npm install` in the Dockerfile. I still don't know why the behaviour was different in Docker than locally, or why `npm uninstall` never finished instead of just taking a long time, but I guess I'm close to the truth wince the fix works..

Conclusion: An imaginator can now be deployed using `nowjs`!
